name: Build Frontend Container

on:
  push:
    branches:
      - main
    paths:
      - 'straftatonlinecup-frontend/**'


  workflow_dispatch:
  
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:

      - name: Add Packer key
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

      - name: Add Packer repo
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install packer

      - name: Install Docker plugin for Packer
        run: sudo packer plugins install github.com/hashicorp/docker

      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        run: |
          sudo mkdir /root/.aws; \
            echo -e "[default]\n" | sudo tee -a /root/.aws/credentials; \
            echo -e "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\n" | sudo tee -a /root/.aws/credentials; \
            echo -e "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}\n" | sudo tee -a /root/.aws/credentials;

      - name: Configure AWS config
        run: |
          echo -e "[default]\n" | sudo tee -a /root/.aws/config; \
            echo -e "region = eu-west-1\n" | sudo tee -a /root/.aws/config;

      - name: Bodge in API URL
        run: |
          sed -i 's%http\:\/\/localhost\:8000%${{ secrets.API_URL }}%g' straftatonlinecup-frontend/index.html
          sed -i 's%http\:\/\/localhost\:8000%${{ secrets.API_URL }}%g' straftatonlinecup-frontend/cups.html
          sed -i 's%http\:\/\/localhost\:8000%${{ secrets.API_URL }}%g' straftatonlinecup-frontend/match.html
          sed -i 's%http\:\/\/localhost\:8000%${{ secrets.API_URL }}%g' straftatonlinecup-frontend/profile.html
          sed -i 's%http\:\/\/localhost\:8000%${{ secrets.API_URL }}%g' straftatonlinecup-frontend/postlogin.html
          sed -i 's%http\:\/\/localhost\:8000%${{ secrets.API_URL }}%g' straftatonlinecup-frontend/info.html
      
      - name: Packer build
        run: cd .build && sudo packer build straftatonlinecup-frontend.pkr.hcl
        env:
          AWS_DEFAULT_REGION: eu-west-1
          
